<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-TopinLite.Workers.LogWorker-8bf8d06a-ab8a-455c-a1c4-de19f169fc21</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2"/>
        <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
        <PackageReference Include="Npgsql" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TopinLite.Domain\TopinLite.Domain.csproj" />
      <ProjectReference Include="..\TopinLite.infra.PostgreSQL\TopinLite.infra.PostgreSQL.csproj" />
    </ItemGroup>
</Project>
