@TopinLite.CrmTransform.ChangeSubscribersOfferingAdd_HostAddress = http://localhost:5254

GET {{TopinLite.CrmTransform.ChangeSubscribersOfferingAdd_HostAddress}}/weatherforecast/
Accept: application/json

###
